(async function () {
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const res = [];
  const ok = (n, p, d) => res.push([n, !!p, d == null ? '' : String(d)]);
  const q = s => document.querySelector(s);
  const click = s => { const el = typeof s === 'string' ? q(s) : s; if (!el) throw new Error('missing ' + s); el.click(); };
  const fire = (el, t) => el.dispatchEvent(new Event(t, { bubbles: true }));
  const S = M.state, H = () => M.h, ST = () => M.store;
  await wait(300);
  try {
    ok('fresh visit shows the example picker', S.ui.modal === 'start' && document.querySelectorAll('.ex-card').length === 11);
    click('[data-act="load-ex"][data-id="laptop"]');
    await wait(100);
    ok('laptop loaded', S.model.name === 'Pick a laptop');
    ok('guide started at step 1', S.ui.guide === 0 && !q('#coach').hidden);
    ok('verdict names a winner', /Fjord Air|Aster 13|Borealis 14/.test(q('.v-title').textContent), q('.v-title').textContent);
    ok('ranking shows 3 passing', document.querySelectorAll('.rank-row').length === 3);
    ok('ruled-out list shows 3', document.querySelectorAll('.out-btn').length === 3);
    click('[data-act="guide-go"][data-v="1"]');
    await wait(50);
    ok('guide step 2 spotlights battery', q('[data-g="crit:battery"]').classList.contains('g-spot'));
    const w = q('[data-in="weight"][data-id="battery"]');
    const before = q('[data-in="weight"][data-id="battery"]');
    w.value = 10; fire(w, 'input');
    ok('dragging does not replace the slider', q('[data-in="weight"][data-id="battery"]') === before);
    ok('share updates live', /\d+%/.test(q('[data-live="share:battery"]').textContent));
    fire(w, 'change');
    await wait(50);
    ok('undo is available', !q('[data-act="undo"]').disabled);
    click('[data-act="undo"]');
    await wait(50);
    ok('undo restores weight', S.model.criteria.find(c => c.id === 'battery').weight === 6);
    click('[data-act="guide-end"]');
    click('[data-act="tab"][data-v="rules"]');
    await wait(50);
    ok('rules tab shows simple builders', document.querySelectorAll('.rule-build').length === 2);
    ok('rule says what it rules out', /Ember 15/.test(q('[data-live="rout:g1"]').textContent));
    const kr = q('[data-in="knob"][data-id="budget"]');
    kr.value = 2000; fire(kr, 'input'); fire(kr, 'change');
    await wait(50);
    ok('raising budget brings more options in', document.querySelectorAll('.rank-row').length === 5, document.querySelectorAll('.rank-row').length);
    ok('who-wins strip rendered', document.querySelectorAll('[data-strip="budget"] .strip-bar span').length >= 1);
    click('[data-act="rule-mode"][data-id="g1"]');
    await wait(30);
    const fx = q('[data-in="rule-fx"][data-id="g1"]');
    fx.value = 'Memroy >= 16'; fire(fx, 'input');
    await wait(30);
    ok('typo gets a suggestion', /Did you mean Memory/.test(q('[data-live="rfx:g1"]').textContent), q('[data-live="rfx:g1"]').textContent);
    ok('formula input survives typing', q('[data-in="rule-fx"][data-id="g1"]') === fx);
    fx.value = 'Memory >= 16'; fire(fx, 'input'); fire(fx, 'change');
    await wait(30);
    ok('fixed formula reads back', /Reads as/.test(q('[data-live="rfx:g1"]').textContent));
    click('[data-act="tab"][data-v="formulas"]');
    click('[data-act="calc-add"]');
    await wait(60);
    const cf = document.querySelectorAll('[data-in="col-fx"]');
    const last = cf[cf.length - 1];
    last.focus(); last.value = 'Price / Battery'; fire(last, 'input'); fire(last, 'change');
    await wait(60);
    const id = last.getAttribute('data-id');
    ok('new formula column computes', typeof S.res.rows[0].vals[id] === 'number', S.res.rows[0].vals[id]);
    ok('formula shows plugged-in numbers', /=/.test(q(`[data-live="cfx:${id}"]`).textContent));
    click(`[data-act="add-crit"][data-id="${id}"]`);
    await wait(60);
    ok('formula column can be scored', S.model.criteria.some(c => c.col === id));
    ok('price-per-hour guessed as more (no keyword) or less', ['more', 'less'].includes(S.model.criteria.find(c => c.col === id).want));
    click('[data-act="tab"][data-v="options"]');
    await wait(40);
    const cell = q('[data-in="cell"][data-id="r1"][data-col="price"]');
    cell.value = '$2,400'; fire(cell, 'input'); fire(cell, 'change');
    await wait(40);
    ok('typing $2,400 stores 2400', S.model.rows[0].v.price === 2400);
    ok('Aster now ruled out by budget', S.res.out.includes('r1'));
    click('[data-act="row-add"]');
    await wait(40);
    ok('add option works', S.model.rows.length === 7);
    click('[data-act="select"][data-id="' + S.res.ranked[1] + '"]');
    await wait(40);
    ok('selecting shows why', /Why/.test(q('.why-head h3').textContent));
    await wait(300);
    ok('checks rendered', document.querySelectorAll('.ck').length >= 1);
    const setupEl = q('#setup'), oldW = setupEl.style.width;
    for (const w of [700, 520, 380]) {
      setupEl.style.width = w + 'px';
      await wait(60);
      const tb = q('#tab-equations').getBoundingClientRect(), sb = q('#setup .tabs').getBoundingClientRect();
      click('[data-act="tab"][data-v="equations"]');
      await wait(60);
      const tb2 = q('#tab-equations').getBoundingClientRect();
      ok(`equations tab reachable in a ${w}px pane`, S.ui.tab === 'equations' && tb2.right <= sb.right + 1 && tb2.left >= sb.left - 1, `${tb.left}-${tb.right} in ${sb.left}-${sb.right}`);
      click('[data-act="tab"][data-v="matters"]');
      await wait(30);
    }
    setupEl.style.width = oldW;
    click('[data-act="tab"][data-v="equations"]');
    await wait(60);
    ok('equations tab lists formulas, rules, points and total', !!q('#eq-column') && !!q('#eq-rule') && !!q('#eq-crit') && !!q('#eq-total'));
    click('[data-act="eq-fmt"][data-v="text"]');
    await wait(30);
    ok('plain text view shows the new formula in full', [...document.querySelectorAll('.eq-code')].some(p => /Price \/ Battery/.test(p.textContent)));
    click('[data-act="eq-fmt"][data-v="tex"]');
    await wait(30);
    ok('LaTeX view shows \\frac', [...document.querySelectorAll('.eq-code')].some(p => /\\frac/.test(p.textContent)));
    click('[data-act="eq-nums"]');
    await wait(30);
    ok('numbers for one option shown', document.querySelectorAll('.eq-nums').length >= 3);
    click('[data-act="eq-fmt"][data-v="math"]');
    await wait(30);
    click('[data-act="open-export"]');
    click('[data-act="exp-tab"][data-v="tex"]');
    await wait(30);
    ok('export has a LaTeX equations document', /\\begin\{document\}/.test(q('.exp-pre').textContent));
    click('[data-act="exp-tab"][data-v="recipe"]');
    await wait(30);
    ok('export summary present', /Ranking/.test(q('.exp-pre').textContent));
    click('[data-act="close-modal"]');
    click('[data-act="open-start"]');
    click('[data-act="open-paste"][data-v="new"]');
    await wait(30);
    const pi = q('#paste-in');
    pi.value = 'Car\tPrice ($)\tSeats\tElectric\nModel A\t32000\t5\tyes\nModel B\t27500\t7\tno\nModel C\t41000\t5\tyes'; fire(pi, 'input');
    await wait(30);
    ok('paste preview counts', /3/.test(q('.paste-pv').textContent));
    click('[data-act="paste-go"]');
    await wait(80);
    ok('pasted table loads', S.model.rows.length === 3 && S.model.columns.length === 3);
    ok('price unit detected', S.model.columns[0].unit === '$');
    ok('electric detected as yes/no', S.model.columns[2].type === 'yesno');
    ok('price guessed lower-is-better', S.model.criteria[0].want === 'less');
    ok('pasted ranking ranks', S.res.ranked.length === 3);
    click('[data-act="open-start"]');
    click('[data-act="load-ex"][data-id="shift"]');
    await wait(80);
    ok('shop example loads with formulas', S.model.columns.filter(c => c.formula).length === 4);
    click('[data-act="open-start"]');
    ok('picker lists all 11 examples', document.querySelectorAll('.ex-card').length === 11, document.querySelectorAll('.ex-card').length);
    click('[data-act="load-ex"][data-id="pharmacy"]');
    await wait(400);
    ok('pharmacy loads', S.model.name === 'Pharmacy staffing plan' && S.res.ranked.length >= 1, S.res.ranked.length);
    ok('situation chips shown', document.querySelectorAll('.sit').length === 7, document.querySelectorAll('.sit').length);
    const before2 = S.res.ranked[0];
    click('[data-act="sit"][data-id="s1"]');
    await wait(400);
    ok('situation applies settings', H().knob('lam').value === 12 && q('.sit.on') && q('.sit.on').dataset.id === 's1');
    click('[data-act="sit"][data-id="base"]');
    await wait(50);
    ok('baseline restores', H().knob('lam').value === 30 && S.res.ranked[0] === before2);
    click('[data-act="tab"][data-v="formulas"]');
    await wait(100);
    ok('settings grouped', document.querySelectorAll('.grp-head').length >= 4, document.querySelectorAll('.grp-head').length);
    const t0 = performance.now();
    const lam = q('[data-in="knob"][data-id="lam"]');
    for (let i = 0; i < 5; i++) { lam.value = 30 + i; fire(lam, 'input'); }
    const dt = (performance.now() - t0) / 5;
    fire(lam, 'change');
    ok('pharmacy drag step under 120 ms', dt < 120, dt.toFixed(1) + ' ms');
    await wait(400);
    ok('day plan strip shows 14 hours', document.querySelectorAll('.hr').length === 14, document.querySelectorAll('.hr').length);
    click('[data-act="open-matrix"]');
    await wait(50);
    ok('matrix opens with safest tag', document.querySelectorAll('.mx tbody tr').length === 9 && !!q('.tag.ok'));
    click('[data-act="close-modal"]');
    click('[data-act="open-find"]');
    await wait(50);
    ok('finder opens with role columns ticked', document.querySelectorAll('.fd-col.on').length >= 3, document.querySelectorAll('.fd-col.on').length);
    click('[data-act="fd-run"]');
    await wait(30);
    ok('finder shows a progress bar while running', !!q('.prog'));
    for (let i = 0; i < 40 && !q('.fd-list li'); i++) await wait(150);
    ok('finder shows results', document.querySelectorAll('.fd-list li').length >= 1);
    ok('finder ran in a background worker', M.runner.usingWorker(), 'worker=' + M.runner.usingWorker());
    const addBtn = q('[data-act="fd-add"]');
    const nRows = S.model.rows.length;
    if (addBtn) { addBtn.click(); await wait(80); }
    ok('finder Add puts a plan into options', !addBtn || S.model.rows.length === nRows + 1);
    click('[data-act="fd-hourly"]');
    for (let i = 0; i < 60 && !q('[data-act="hf-add"], .fd-res .hint'); i++) await wait(150);
    ok('plan by hour with new options shows a sequence', document.querySelectorAll('.fd-res .hrly-list li').length >= 1);
    click('[data-act="close-modal"]');
    click('[data-act="hr-run"]');
    for (let i = 0; i < 40 && !q('.hrly'); i++) await wait(150);
    ok('hour-by-hour plan shown', !!q('.hrly-bar') && document.querySelectorAll('.hrly-list li').length >= 1);
    click('[data-act="open-compare"]');
    click('[data-act="cmp-pin"]');
    await wait(40);
    click('[data-act="close-modal"]');
    ST().change(m => { m.criteria.find(c => c.id === 'wait').weight = 1; }, { setup: true });
    await wait(40);
    click('[data-act="open-compare"]');
    await wait(40);
    ok('compare lists the change', /Short wait|wait/i.test(q('.cmp-diff') ? q('.cmp-diff').textContent : ''), q('.cmp-diff') && q('.cmp-diff').textContent);
    ok('compare shows both rankings', document.querySelectorAll('.cmp-t tbody tr').length === S.model.rows.length);
    click('[data-act="close-modal"]');
    ST().load(M.examples.get('flat'));
    await wait(300);
    ok('flat: soft penalty tag in ranking', !!q('.rank-row .tag.bad'));
    click('[data-act="tab"][data-v="rules"]');
    await wait(40);
    click('[data-act="rule-kind"][data-id="g2"][data-v="hard"]');
    await wait(40);
    ok('switching soft → hard rules options out', S.res.out.length >= 2, S.res.out.length);
    click('[data-act="open-pairs"]');
    await wait(40);
    const pa = q('[data-in="pr-a"]'), pb = q('[data-in="pr-b"]');
    pa.value = 'r4'; fire(pa, 'change'); await wait(20);
    q('[data-in="pr-b"]').value = 'r1'; fire(q('[data-in="pr-b"]'), 'change'); await wait(20);
    click('[data-act="pr-add"]');
    await wait(30);
    ok('pair added', S.model.pairs.length === 1);
    click('[data-act="pr-fit"]');
    await wait(200);
    ok('fit gives an answer', !!q('.pr-fit'));
    void pb;
    click('[data-act="close-modal"]');
    ['feed', 'venue', 'cafe', 'care'].forEach(id => { ST().load(M.examples.get(id)); ok(id + ' loads and ranks', S.res.ranked.length >= 1 && !S.res.issues.length, S.res.issues.map(x => x.msg).join(';')); });
  } catch (e) { ok('script error', false, e.message + ' ' + e.stack); }
  const fail = res.filter(r => !r[1]);
  console.log(`UI ${res.length - fail.length}/${res.length}`);
  fail.forEach(f => console.log('FAIL ' + f[0] + ' :: ' + f[2]));
})();
